config/routes.rb
Whispered::Application.routes.draw do
  root :to => 'welcome#index'

  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout

  resources :inquiries, :only => [:index, :show] do
    collection do
      get 'search'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def login_required
    redirect_to root_path unless session[:current_user]
  end

  def current_user
    session[:current_user]
  end

  def current_user=(user)
    session[:current_user] = user
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_filter :login_required

  respond_to :html

  def index
    @inquiries = DynamicModel.all.map{|model| model.limit(5)}.flatten
  end

  def search
    @inquiries = DynamicModel.all.map {|model|
      model.find(model.search(params[:q]).map(&:_id))
    }.flatten
    @inquiries = Kaminari.paginate_array(@inquiries).page(params[:page]).per(10)
  end

  def show
    @inquiry = params[:class_name].constantize.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if Settings.members.include? request.env['omniauth.auth'][:info][:nickname]
      self.current_user = request.env['omniauth.auth'][:info]
    else
      flash[:error] = "Access denied, You can't have permissions."
    end
    redirect_to root_path
  end

  def destroy
    session[:current_user] = nil
    redirect_to '/', :notice => "Signed out"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inquiries/_results.html.slim
- @inquiries.each do |inquiry|
  .row-fluid
    .span12
      .fieldset
        .legend = link_to inquiry.send(inquiry.class.primary_key.to_sym), inquiry_path(inquiry, :class_name => inquiry.class)
        table.table
          - inquiry.class.text_columns.each do |c|
            - next unless inquiry.class.display_columns.include? c
            tr
              td= c.to_s
              td= truncate(inquiry.send(c.to_sym), length: 140)
          - if inquiry.class.settings.created_at
            tr
              td= inquiry.class.settings.created_at.to_s
              td= inquiry.send(inquiry.class.settings.created_at.to_sym)

app/views/inquiries/index.html.slim
= render :partial => 'results', :locals => {:inquiries => @inquiries}

app/views/inquiries/search.html.slim
= paginate @inquiries
= render :partial => 'results', :locals => {:inquiries => @inquiries}
= paginate @inquiries

app/views/inquiries/show.html.slim
p#notice
  = notice

.fieldset
  .legend = @inquiry.send(@inquiry.class.primary_key.to_sym)
  table.table
    - @inquiry.class.text_columns.each do |c|
      tr
        td= c.to_s
        td
          pre= raw(@inquiry.send(c.to_sym))
    - if @inquiry.class.settings.created_at
      tr
        td= @inquiry.class.settings.created_at.to_s
        td= @inquiry.send(@inquiry.class.settings.created_at.to_sym)

= link_to 'Back', inquiries_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Whispered
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          - if current_user
            ul.nav
              li = link_to "Home", root_path
              li = link_to "Inquiry", inquiries_path
              li
                form.navbar-form action="/inquiries/search"
                  input.span4 type="text" name="q" placeholder="search" value="#{params[:q]}"
                  button.btn type="submit" Search

            p.navbar-text.pull-right.dropdown
              = image_tag(current_user[:image], {:size => "16x16"}) + " " + current_user[:nickname] + " "
              = link_to raw("<i class=icon-off></i>"), signout_path

    .container
      = yield

app/views/welcome/index.html.slim
- unless current_user
  .hero-unit
    h1 Whispered
    p awesome inquiry management
    p = link_to "Sign in with github", "/auth/github", :class => "btn btn-primary btn-large"